Repository 2024-Winter-Bootcamp-Team-A/backend, pull requests merged in 2025-01, with the labels that each got.

#7 [feat] 회원가입 기능 구현
  README.md
Labels: 기능구현

#9 [feat] 회원가입 삭제
  README.md
Labels: 기능구현

#11 [feat] 기능 구현
  README.md
Labels: 기능구현

#13 [feat] 테스트
  README.md
Labels: 기능구현

#15 [feat] 내용
  README.md
Labels: 기능구현

#17 [chore] 장고 초기 세팅
  .gitignore
  ateam/__init__.py
  ateam/asgi.py
  ateam/settings.py
  ateam/urls.py
  ateam/wsgi.py
  manage.py
Labels: 기타/세팅

#28 [feat] 책 정보 저장 구현
  ateam/settings.py
  ateam/urls.py
  books/__init__.py
  books/admin.py
  books/apps.py
  books/migrations/0001_initial.py
  books/migrations/__init__.py
  books/models.py
  books/serializers.py
  books/tests.py
  books/urls.py
  books/views.py
Labels: 기능구현

#33 [feat]회원가입 구현
  ateam/settings.py
  ateam/urls.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_user_created_at_user_is_deleted_user_password_and_more.py
  users/migrations/0003_alter_user_sex.py
  users/migrations/__init__.py
  users/models.py
  users/serializers.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: 기능구현

#35 [feat] 로그인 기능 구현
  ateam/settings.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: 기능구현

#37 [feat] 숏츠 생성 API 구현 (값 수동 입력)
  ateam/settings.py
  ateam/urls.py
  shorts/__init__.py
  shorts/admin.py
  shorts/apps.py
  shorts/migrations/0001_initial.py
  shorts/migrations/__init__.py
  shorts/models.py
  shorts/serializers.py
  shorts/tests.py
  shorts/urls.py
  shorts/views.py
Labels: 기능구현

#39 [feat] 회원정보 조회 기능 구현
  users/urls.py
  users/views.py
Labels: 기능구현

#43 [feat] 위시리스트 추가 & 삭제 기능 구현
  ateam/settings.py
  ateam/urls.py
  requirements.txt
  wishes/__init__.py
  wishes/admin.py
  wishes/apps.py
  wishes/migrations/0001_initial.py
  wishes/migrations/__init__.py
  wishes/models.py
  wishes/serializers.py
  wishes/tests.py
  wishes/urls.py
  wishes/views.py
Labels: 기능구현

#47 [feat] 댓글 생성 & 삭제 & 전체 조회 기능 구현
  ateam/settings.py
  ateam/urls.py
  comments/__init__.py
  comments/admin.py
  comments/apps.py
  comments/migrations/0001_initial.py
  comments/migrations/__init__.py
  comments/models.py
  comments/serializers.py
  comments/tests.py
  comments/urls.py
  comments/views.py
Labels: 기능구현

#51 [feat] 책 개별 저장 API 추가
  books/models.py
  books/serializers.py
  books/urls.py
  books/views.py
  page_source.html
Labels: 기능구현

#54 [feat] 링크 공유 수 증가 기능 구현
  books/migrations/0004_alter_book_book_url.py
  shorts/urls.py
  shorts/views.py
Labels: 기능구현

#56 [feat] 통계 기능 구현
  ateam/settings.py
  ateam/urls.py
  comments/migrations/0002_alter_comment_book.py
  comments/models.py
  shorts/views.py
  stats/__init__.py
  stats/admin.py
  stats/apps.py
  stats/migrations/__init__.py
  stats/models.py
  stats/tests.py
  stats/urls.py
  stats/views.py
Labels: 기능구현

#59 [feat] 유저 정보조회 api 수정
  users/views.py
Labels: 기능구현

#61 [feat] 오늘의 숏츠 API
  ateam/settings.py
  ateam/urls.py
  todays_shorts/__init__.py
  todays_shorts/admin.py
  todays_shorts/apps.py
  todays_shorts/migrations/0001_initial.py
  todays_shorts/migrations/__init__.py
  todays_shorts/models.py
  todays_shorts/tests.py
  todays_shorts/urls.py
  todays_shorts/views.py
Labels: 기능구현

#65 [feat] 마이페이지 유저 기록 상세 api
  records/urls.py
  records/views.py
  todays_shorts/urls.py
  todays_shorts/views.py
  wishes/urls.py
  wishes/views.py
Labels: 기능구현

#73 [feat] faqs api
  ateam/settings.py
  ateam/urls.py
  faqs/__init__.py
  faqs/admin.py
  faqs/apps.py
  faqs/migrations/0001_initial.py
  faqs/migrations/__init__.py
  faqs/models.py
  faqs/serializers.py
  faqs/tests.py
  faqs/urls.py
  faqs/views.py
  requirements.txt
Labels: 기능구현

#75 [feat] 숏츠 개별, 베스트 조회 api
  shorts/serializers.py
  shorts/urls.py
  shorts/views.py
Labels: 기능구현

#77 [feat] 오늘의 숏츠 API 오류 수정
  docker-compose.yml
  requirements.txt
  todays_shorts/migrations/0001_initial.py
  todays_shorts/migrations/0002_alter_todaysshorts_book_id_and_more.py
  todays_shorts/models.py
  todays_shorts/views.py
Labels: 오류수정

#78 [feat] 숏츠 검색 api
  shorts/urls.py
  shorts/views.py
  todays_shorts/views.py
  users/views.py
Labels: 기능구현, 오류수정

#80 [feat] 숏츠 조건별 조회 API
  shorts/urls.py
  shorts/views.py
  todays_shorts/views.py
Labels: 기능구현

#82 [fix] 회원가입 성별 api
  users/migrations/0004_alter_user_sex.py
  users/models.py
  users/serializers.py
Labels: 오류수정

#84 [feat] Most Popular Shorts API
  stats/urls.py
  stats/views.py
Labels: 기능구현

#85 [feat] 숏츠 개별조회 2 api
  shorts/serializers.py
  shorts/urls.py
  shorts/views.py
  stats/urls.py
Labels: 기능구현

#89 [fix] 시청기록 위시리스트 전체보기 response 수정
  elk/beat/filebeat.yml
  elk/elasticsearch/elasticsearch.yml
  elk/kibana/kibana.yml
  elk/logstash/logstash.conf
  elk/logstash/logstash.yml
  records/views.py
  wishes/views.py
Labels: 오류수정

#92 [feat] 영상 생성 API
  Dockerfile
  ateam/settings.py
  books/gpt_point.py
  books/gpt_prompt.py
  books/gpt_script.py
  books/urls.py
  books/utils.py
  books/views.py
  requirements.txt
  shorts/HMKMRHD.TTF
  shorts/background.mp3
  shorts/crop.py
  shorts/dalle.py
  shorts/gen_video.py
  shorts/image_move_audio.py
  shorts/s3.py
  shorts/serializers.py
  shorts/tts.py
  shorts/urls.py
  shorts/views.py
  test.wav
Labels: 기능구현

#94 [fix] 프롬프팅 개선
  books/gpt_script.py
  shorts/image_move_audio.py
  shorts/views.py
Labels: 기능구현

#96 [feat] 책, 숏츠 삭제 api 구현
  books/urls.py
  books/views.py
  shorts/views.py
Labels: 기능구현

#99 [feat] 로깅
  docker-compose.yml
  elk/beat/filebeat.yml
  elk/elasticsearch/elasticsearch.yml
  elk/kibana/kibana.yml
  elk/logstash/logstash.conf
  elk/logstash/logstash.yml
  promtail/config.yaml
  requirements.txt
Labels: 기능구현

#97 [feat] 크롤링 수정 & 스케쥴링
  Dockerfile
  ateam/__init__.py
  ateam/celery.py
  ateam/settings.py
  books/tasks.py
  books/utils.py
  celerybeat-schedule-shm
  celerybeat-schedule-wal
  docker-compose.yml
  requirements.txt
Labels: 오류수정

#101 [feat] 숏츠 조회 API 수정
  shorts/serializers.py
Labels: 기능구현
